### ISSUE TITLE
mailAbooks.pl send out empty attachments

### ISSUE THREAD

**Issue by sneader** [loweryaustin/cpanel-squirrelmail-exporter#1] opened 2019-02-20 22:33 UTC
When we run mailAbooks.pl it does everything it should, except the attached .csv file is completely blank, not even the  headers are in it.

**Comment by loweryaustin** [comment] 2019-02-21 04:13
That's very interesting. I've just logged into my server to see if I can reproduce the issue. I should have some info shortly.

**Comment by loweryaustin** [comment] 2019-02-21 04:23
I was able to reproduce the issue. Sorry about that. I'm working on a fix now. Stay tuned.

**Comment by loweryaustin** [comment] 2019-02-21 04:35
Looks like it comes down to this portion of the code:
```
                open( my $fh, "<", $file) or die "Can't open < $file: $!";
                my $file_content = do { local $/; <$fh> };
                if ($count == 1 and $file_content =~ "Nickname" ) { message ("NOTICE: $file appears to only contain header information so it has been skipped and not mailed.", 1, 1, 0); next; }
                my %attachment;
                $attachment{'content'} = $fh;
```
The attachment should be the file handle or a scalar reference. I thought I was using the correct method to assign the file handle to the hash value, but it looks like that's not working.

**Comment by loweryaustin** [comment] 2019-02-21 04:57
Ah ha! Found the issue. I failed to close the filehandle properly at the end of the loop. I hadn't needed to close filehandles before when I wasn't looping on them, so I this was an issue with my inexperience with perl. Again I'm sorry about that. I'll have a fix pushed for this in the next few moments.

**Comment by loweryaustin** [comment] 2019-02-25 12:39
I apologize for the delay.
This has been fixed with the following commit:
https://github.com/loweryaustin/cpanel-squirrelmail-exporter/commit/ae8090a586d0aca8dc91916557c311260789f34f

**Closed as completed by loweryaustin** 2019-02-25 12:39 UTC
